### ISSUE TITLE
Comma before "km"

### ISSUE THREAD

**Issue by sylas** [ljmerza/travel-time-card#11]
Current card displays:
![obraz](https://user-images.githubusercontent.com/1716833/74814463-9ba67a80-52f7-11ea-8667-77485ed62165.png)
Should be: **16 km** (or 16.0 km) and **28 km** (or 28.0 km), without " ,". I am using Google Maps, Maybe it's a localization issue (I am from Poland).

**Comment by ljmerza** [comment]
What are the raw states/attributes for these entities? They might have commas in them that aren't being stripped.

**Comment by sylas** [comment]
Attributes "distance" of the sensors are:
```
distance: 16,3 km
distance: 28,6 km
```
and the final formatting on the card is like in the opening post.
