### ISSUE TITLE
Units override

### ISSUE THREAD

**Issue by holdestmade** [ljmerza/travel-time-card#5]
Could we have a setting for imperial / metric units ? in the UK we are metric, but not for distance, we still use miles.....

Also a rounding of the units would be useful as the HERE integration 

https://github.com/eifinger/here_travel_time/releases/tag/v1.2.1

has distance like this:  51.234875287873873

**Comment by ljmerza** [comment]
added in v1.1.0

**Comment by holdestmade** [comment]
Thanks works great
