### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by holdestmade** [ljmerza/travel-time-card#7]
Getting this error in my logs and in lovelace it is showing:

`Custom element doesn't exist: travel-time-card.`

Have updated to v1.1.1 and done refresh/restart. It did work on first update but now will not:

Related to this ?
[https://github.com/ljmerza/travel-time-card/issues/6]

Update:
I can get it to show sometimes by refreshing the browser (CTRL F5) but if I navigate away / refresh the page in lovelace and back it shows as not existing again

**Comment by ljmerza** [comment]
sounds like a caching issue. can you try clearing your cache?

**Comment by holdestmade** [comment]
Yes I tried refresh and clearing cache. I downgraded to 1.0.0 and it works fine

**Comment by cjsmns** [comment]
Hmm. I've got this error happening as well. CTRL+F5 doesn't work, downgrading to v1.0.0 also doesn't work. Not sure what happened as it was working fine, then it wasn't. No changes have been made to my system.

**Comment by aluisperezh** [comment]
It happens in my HA too, exactly with the same symptoms as above.

Waiting on 1.0.0 for a solution. Thanks for your work...

**Comment by ljmerza** [comment]
ok i tried reverting back to the old build process in v1.1.2 see if that works

**Comment by holdestmade** [comment]
Works perfect now, many thanks !

Got to love the ease of updating with HACS......2 minutes after you posted all working !
